const datos = [
    {
      id:0,
      img: "/img/ensalada.jpg",
      nombre: "PrimeraEnsalada",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: "4",
    },
    {
      id:1,
      img: "/img/ensalada.jpg",
      nombre: "Segundo",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: "4",
    },
  
    {
      id:2,
      img: "/img/tacos.jpg",
      nombre: "Tacos al Pastor",
      descripcion: "Tacos con carne al pastor",
      tipo: "Tacos",
      origen: "México",
      precio: 15000,
      disponibilidad: false,
      promocion: "No",
      cantidadPorcion: "Individual",
      puntuacion: 5,
    },
  
    {
      id:3,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
  
    {
      id:4,
      img: "/img/ensalada.jpg",
      nombre: "Ensalada César",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:5,
      img: "/img/ensalada.jpg",
      nombre: "Quinto",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:6,
      img: "/img/ensalada.jpg",
      nombre: "Ensalada César",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:7,
      img: "/img/ensalada.jpg",
      nombre: "Ensalada César",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:8,
      img: "/img/ensalada.jpg",
      nombre: "Ensalada César",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:9,
      img: "/img/ensalada.jpg",
      nombre: "ultimo",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:10,
      img: "/img/ensalada.jpg",
      nombre: "Ensalada César",
      descripcion: "Ensalada con ingredientes variados...",
      tipo: "Ensalada",
      precio: 10000,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:11,
      img: "/img/tacos.jpg",
      nombre: "Todos los 11 son pruebas",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:12,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:13,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:14,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:15,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:16,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:17,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:18,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:19,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:19,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:20,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:21,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:22,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:23,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:24,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:25,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:26,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:27,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:28,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:29,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:30,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:31,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:32,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:33,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:34,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:35,
      img: "/img/tacos.jpg",
      nombre: "11",
      descripcion: "11",
      tipo: "11",
      precio: 11,
      disponibilidad: true,
      origen: "No especificado",
      promocion: "2x1",
      cantidadPorcion: "Individual",
      puntuacion: 4,
    },
  
    {
      id:37,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:38,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:39,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:40,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:41,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:42,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:43,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:44,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:45,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:46,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:47,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:48,
      img: "/img/vino.jpg",
      nombre: "Cariñoso",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
    {
      id:49,
      img: "/img/vino.jpg",
      nombre: "Ultimo",
      descripcion: "Vino con notas de uva",
      tipo: "Vino",
      origen: "España",
      precio: 120000,
      disponibilidad: true,
      promocion: "Acompañante incluido",
      cantidadPorcion: "10 copas",
      puntuacion: 5,
    },
  ];